### ISSUE TITLE
win32api (LoadError) on Ubuntu 12.10 / rvm ruby-1.9.3-p385

### ISSUE THREAD

**Issue by robertgzr** [ashbb/green_shoes#76]
`require': cannot load such file -- win32api (LoadError)

constantly getting this error when I am trying to execute example58.rb from Sublime Text 2
![Screenshot from 2013-03-21 13:19:21](https://f.cloud.github.com/assets/3930615/285576/eeb64a46-9221-11e2-997c-cf97cf37c732.png)

**Comment by ashbb** [comment]
@robtg Thanks for pointing out this issue. I've read the post about the same issue in the Shoes ML recently. I paste the dialogue here. It's not a solution, though...

---

Hi,

Is it possible for someone to test the video player on Linux?

I'm using Ubuntu 12.10 and green shoes. I've tried running the sample
code from the green shoes manual
http://ashbb.github.com/green_shoes/Video.html

and playing anything from a youtube video to a local mp3 and I always
get this error:

/home/sebastjan/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- win32api (LoadError)

thx
seba

---

Hi Seba, J and folks,

It may be my fault...
Could you try out the following patch?

D:\green_shoes\lib\plugins>diff video_old.rb video.rb
105c105
<       require 'win32api'
---
>       require 'win32api' if RUBY_PLATFORM =~ /mingw/

Regards,
ashbb

---

After patching I get the error below when I run the sample code from
green shoes manual. The app opens but no video is displayed. When play
is pressed the app crashes and the error is shown:

/home/sebastjan/.rvm/gems/ruby-1.9.3-p194/gems/green_shoes-1.1.365/lib/plugins/video.rb:45:in `play': undefined method`xwindow_id=' for nil:NilClass
         from video.rb:15:in `block (2 levels) in <main>'

regards
seba

---

Hi Seba,

Thanks for taking your time.
Umm,... need to find one more solution for Linux. :-P

Thanks again,
ashbb
